### ISSUE TITLE
Suggestion: Single Page per Datasheet

### ISSUE THREAD

**Issue by RhoxFett** [rweyrauch/PrettyScribe#100]
Hey there! Love the app - the only thing i find missing (due to the way I like to put together binders for datasheets/stratagems with Buttscribe) is the option to print it off (admittedly wastefully) with just a single unit's datasheet per page.  That option would be a great help.  Thanks!

**Comment by mardanbeigi** [comment]
This issue is fixed now, take it for a spin!

**Comment by RhoxFett** [comment]
Absolutely perfect my friend, thanks!
