### ISSUE TITLE
Horus Heresy W30k .rosz not rendering

### ISSUE THREAD

**Issue by CyberC10** [rweyrauch/PrettyScribe#103]
When I select a .rosz file from Warhammer 30k (2nd edition), nothing loads (blank page). This issue does not occur when I upload a W40k .rosz file.

**Comment by mplonski127** [comment]
Seconded.  We've got a big HHv2 community around here, and I have to bring my Battlescribe rosters into Word to make them more user friendly.

**Comment by mardanbeigi** [comment]
Please provide a simple roster file that is not loading and I’ll take a look

**Comment by mardanbeigi** [comment]
Put the roster in a zip file, and you’ll be able to attach

**Comment by CyberC10** [comment]
[DA 2K.rosz.zip](https://github.com/rweyrauch/PrettyScribe/files/10427838/DA.2K.rosz.zip)

Here you go.

**Comment by mplonski127** [comment]
Here's one from me.  Thanks!

**Comment by rweyrauch** [comment]
I started on adding HHv2 late last year.   It seems that is interest and I'll start the work again.   How would like to see the data displayed?  40k-ish or more inline with the HH layout?

**Comment by mplonski127** [comment]
I admit I just discovered Pretty Scribe in the past couple of
      weeks, so I don't know what the HH1 layout looked like.  The 40k
      one is nice enough for me to ask for HH2 to be incorporated, so,
      really, whatever you choose.
    Matt Plonski
    
    On 1/16/2023 2:49 PM, Rick Weyrauch
      wrote:
    
    
      
      I started on adding HHv2 late last year. It seems
        that is interest and I'll start the work again. How would like
        to see the data displayed? 40k-ish or more inline with the HH
        layout?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/rweyrauch/PrettyScribe/issues/103#issuecomment-1384485942",
"url": "https://github.com/rweyrauch/PrettyScribe/issues/103#issuecomment-1384485942",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CyberC10** [comment]
Same, so 🤷🏻‍♂️. Appreciate the work on it!

**Comment by mardanbeigi** [comment]
SG Rick, will let you handle. In the meantime, sent you a pull request to fix the error message that should be shown for unsupported rosters

**Comment by rweyrauch** [comment]
After entirely too long, very limited 2nd Ed. HH has been added to PrettyScribe.   Much work remains and not everything is handled correctly.    But enough is in place to solicit feedback and what you want to see.
