### ISSUE TITLE
Unit names and points costs not visible in printing.

### ISSUE THREAD

**Issue by Beornwulf** [rweyrauch/PrettyScribe#105]
So far I've encountered it in a 40k roster.

I believe adding `print-color-adjust: exact;` to the `table-dark` class in the print media query should fix it.

Screensnip of the behaviour I'm seeing:

![image](https://user-images.githubusercontent.com/5617122/216139867-96af7bd6-00e1-4b1f-b209-13ffa66b44e8.png)

**Comment by mardanbeigi** [comment]
Thanks for the report, please confirm you're on Firefox. I'll submit the fix, we were using the -webkit-print-color-adjust which wouldn't cover Firefox.

**Comment by Beornwulf** [comment]
> Thanks for the report, please confirm you're on Firefox. I'll submit the fix, we were using the -webkit-print-color-adjust which wouldn't cover Firefox.

confirming Firefox, that makes sense - thanks
