### ISSUE TITLE
Age of Sigmar - Missing GHB Rules Section

### ISSUE THREAD

**Issue by TheStreamBox** [rweyrauch/PrettyScribe#109]
Love Prettyscribe, what a great tool. Thanks!

I've noticed that the output for Age of Sigmar BS rosters doesn't include the section for GHB Rules (2023 in this case). Is this intentionally removed or a bug? It'd be great to have the relevant rules section added to the roster output from PS if possible.

Cheers

![ghb 2023 rules](https://user-images.githubusercontent.com/126950472/222889824-dfee4ee3-ff1b-49e0-9cfa-19beb24cdaf6.png)

**Comment by rweyrauch** [comment]
The rules display was not added to the AoS output.  I'll add them.
