### ISSUE TITLE
Missing Psychomancer's ability effects description

### ISSUE THREAD

**Issue by monkeyofficial** [rweyrauch/PrettyScribe#110]
Psychomancer's "Harbringer of Despair" ability effects descriptions are missing when I open roster file in prettyscribe

[Roster file.zip](https://github.com/rweyrauch/PrettyScribe/files/10940558/Necrons.new.zip)

![BattleScribe screenshot](https://user-images.githubusercontent.com/41269467/224279625-571ab395-754d-407d-afdc-963fc5d848cf.jpg)

![PrettyScribe screenshot](https://user-images.githubusercontent.com/41269467/224279775-fedb16dd-7402-481f-9912-13d683ac372b.jpg)

**Comment by mardanbeigi** [comment]
Thanks for the bug report, I submitted a fix and pull request
