### ISSUE TITLE
WH40k 9th rosters weapons and subfaction rules don't show

### ISSUE THREAD

**Issue by mardanbeigi** [rweyrauch/PrettyScribe#12]
I noticed a couple problems when using PrettyScribe on a small Necrons force with WH40k 9th edition setup:
[Necron June 2021 2.zip](https://github.com/rweyrauch/PrettyScribe/files/6835123/Necron.June.2021.2.zip)

- weapons don't always show up. poking around: the Royal Warden's <profile typeName="Unit"> information is listed after its <profile typeName="Weapon"> information (which is nested inside a <selection>), so the method CreateUnit fails nukes the weapon info when it sees the unit info: https://github.com/rweyrauch/PrettyScribe/blob/a1e185f19e9527bff1781287ca2d5cd360b7e4a0/src/roster40k.ts#L585. All units have this problem.

- custom dynasties info don't show up either. the subfaction rules are listed as "Dynastic Code" rather than "Abilities", so the rules aren't extracted

**Comment by mardanbeigi** [comment]
Thanks for tackling. This works with the Necron force, where specific models in a unit only have a single weapon. However, I'm seeing wrong results for this test BA army:
[BloodAngels test.zip](https://github.com/rweyrauch/PrettyScribe/files/6858757/BloodAngels.test.zip)

Lieutenant weapons are missing, Assault intercessors are missing weapon loadouts but sgt has multiple dupe weapons

**Comment by mardanbeigi** [comment]
btw happy to submit a patch with a quick fix if that's helpful

**Comment by rweyrauch** [comment]
A patch is fine.  I can merge and test.

**Comment by rweyrauch** [comment]
I fixed a regression yesterday on missing weapons.  Please retest.  The BA list you posted appears to display correctly with the most recent version.

**Comment by mardanbeigi** [comment]
Things didn't look right to me even with your latest fix. I sent you pull request with fixes for the weapons, plus a few other minor fixes: #16
