### ISSUE TITLE
Suggestion to add roster notes

### ISSUE THREAD

**Issue by Vinestou** [rweyrauch/PrettyScribe#128]
Hi,

Currently it is possible to see custom names an notes on unit cards.

Would it be possible to add the general 'notes' also? Its under the Roster details tab on top and if you share the Battlescribe list it is added to the file under the list name.

![image](https://github.com/rweyrauch/PrettyScribe/assets/52471580/a20b9c88-134d-41a0-8333-8458e7d4f7df)
![image](https://github.com/rweyrauch/PrettyScribe/assets/52471580/7660749f-e3f4-4433-b1f1-3e3596896f51)

Thanks!

**Comment by rweyrauch** [comment]
Yes.  We allow this in 40k. It can be added to AoS as well.

**Comment by Vinestou** [comment]
@rweyrauch My question is for 40k. AoO stands for Arks of Oman.

 The Notes doesn't work  unfortunately. PrettyScribe is not printing / showing my notes.

**Comment by rweyrauch** [comment]
Oops.  Notes for 40k are implemented.   Could you post a roster that shows the problem?

**Comment by rweyrauch** [comment]
Can you cut-and-paste the roster file contents into the issue comments?

**Comment by Vinestou** [comment]
New Roster test (Warhammer 40,000 9th Edition) [12CP]
test prettyscribe Notes
test prettyscribe Notes
test prettyscribe Notes
test prettyscribe Notes
Arks of Omen Detachment (Chaos - Thousand Sons) [12CP]
Rules: Brotherhood of Sorcerers
Configuration [12CP]
Battle Size [12CP]
Selections: 3. Strike Force (101-200 Total PL / 1001-2000 Points) [12CP]
Categories: Configuration
Cults of the Legion
Selections: *No Cult*
Categories: Configuration
Detachment Command Cost
Categories: Configuration
Game Type
Categories: Configuration
Force Rules
Brotherhood of Sorcerers: If your army is Battle-forged, THOUSAND SONS units in THOUSAND SONS Detachments gain the following abilities
- Add 1 to Psychic tests taken for this unit.
- If this unit is ARCANA ASTARTES or TZAANGOR, each model in this unit has a 5+ invulnerable save. ()

Created with [BattleScribe](https://www.battlescribe.net/)

@rweyrauch

**Comment by Vinestou** [comment]
@rweyrauch hi Sorry for the ping. Did I paste the correct content?

**Comment by rweyrauch** [comment]
Yes.  I have enough info to recreate the problem.
