### ISSUE TITLE
40K 10 Edition Update

### ISSUE THREAD

**Issue by shadow102984** [rweyrauch/PrettyScribe#133]
I’m getting a error message that Warhammer 40,000 10th Edition is not supported. Will there be a update to fix this? Thanks.

**Comment by rweyrauch** [comment]
Yes.  The 10th ed catalogs just dropped a few days ago.   Prettyscribe support for 10th will follow soon.

**Comment by Vinestou** [comment]
Hi Sorry for the bump. Any update on 10th? The error is gone, so is it fully functional now?

**Comment by rweyrauch** [comment]
Basic 10th ed support is functional.   The formatting remains 8th ed style for now.   
Additional feedback/requests are welcome.
