### ISSUE TITLE
Missing and duplicate sections within a unit block from .ROSZ import

### ISSUE THREAD

**Issue by Ironscyde** [rweyrauch/PrettyScribe#138]
**Current**
When importing a .ROSZ file previously I would see section about the 'UNIT' with the characteristics like Movement, Toughness, etc but in some cases this has disappered and instead skips straight to the weapon profiles. In some cases the 'UNIT' section is there but only includes one of the profiles or duplicates.

I have also noticed various duplicate weapon profiles in both the 'RANGED' and 'MELEE' sections.

![image](https://github.com/rweyrauch/PrettyScribe/assets/141408324/b237b178-9429-4364-856e-5a76decb9a75)
![image](https://github.com/rweyrauch/PrettyScribe/assets/141408324/f0bb1ac7-bebc-4c64-9cff-0d4e396dfe6c)
![image](https://github.com/rweyrauch/PrettyScribe/assets/141408324/bc35be00-9233-41de-8ace-9f96e604cbc9)

**Expected**
Each unit block should contain one copy of all applicable 'UNIT', 'RANGED WEAPON, 'MELEE WEAPON' profile.

---
I was wondering if Battlescribe (v. 2.03.21) or the Battlescribe Data (v. 10.1.4)has changed how it's now recording model configurations. So when I equip a special weapon, that "model" is being treat as it's own entity (i.e. has it's own 'UNIT' profile, any basic loadout weapons are duplicated etc). Not sure why that would cause some 'UNIT' profiles to disapear though unless there is a limit. I've attached my .ROSZ (changed the file type to .txt to allow it to be uploaded) and a PDF from PrettyScribe as well as how Battlescribe exports my list.

[01  LoV  Leviathan  v0102.txt](https://github.com/rweyrauch/PrettyScribe/files/12776681/01.LoV.Leviathan.v0102.txt)

[PrettyScribe 01 _ LoV _ Leviathan _ v0102.pdf](https://github.com/rweyrauch/PrettyScribe/files/12776682/PrettyScribe.01._.LoV._.Leviathan._.v0102.pdf)

[01  LoV  Leviathan  v0102.html.pdf](https://github.com/rweyrauch/PrettyScribe/files/12776685/01.LoV.Leviathan.v0102.html.pdf)

**Comment by rweyrauch** [comment]
Thanks for the detailed error report.  
I'll investigate the display errors you reporting.

**Comment by bo0ples** [comment]
I’m having the same issues as Ironscyde but noticed that it’s only affecting 10E exports. I’ve attached two similar rosters from BS, one being from 9th and the other from 10th, which will show the differences. 

[PrettyScribe Ultramarines_9E.pdf](https://github.com/rweyrauch/PrettyScribe/files/12807590/PrettyScribe.Ultramarines_9E.pdf)
[PrettyScribe Ultramarines_10E.pdf](https://github.com/rweyrauch/PrettyScribe/files/12807593/PrettyScribe.Ultramarines_10E.pdf)
[Ultramarines_9E.rosz.txt](https://github.com/rweyrauch/PrettyScribe/files/12807595/Ultramarines_9E.rosz.txt)
[Ultramarines_10E.rosz.txt](https://github.com/rweyrauch/PrettyScribe/files/12807596/Ultramarines_10E.rosz.txt)
[Ultramarines_9E_BS.pdf](https://github.com/rweyrauch/PrettyScribe/files/12807601/Ultramarines_9E_BS.pdf)
[Ultramarines_10E_BS.pdf](https://github.com/rweyrauch/PrettyScribe/files/12807602/Ultramarines_10E_BS.pdf)

**Comment by rweyrauch** [comment]
I reverted the most recent changes the broke a few things.

**Comment by mardanbeigi** [comment]
Thanks Rick, I have an idea what the underlying problem is, the example ros files are great test cases that I'll add and then take a stab at a fix forward

**Comment by rweyrauch** [comment]
Great.  I looked at the code but decided it would be easier to revert and work on fix later.
