### ISSUE TITLE
Horus Heresy 2.0 - Not Displaying Statlines

### ISSUE THREAD

**Issue by crazymunch** [rweyrauch/PrettyScribe#144]
When loading a Horus Heresy 2.0 roster file, statlines will display on some files but not others - I have found older files (from older patches of Battlescribe) seem to work, while newer ones don't. 

Github won't allow me to upload a ROSZ, is there a good way to send it to you?

**Comment by rweyrauch** [comment]
You could resave the roster as the uncompressed ROS file and upload the roster that way.

What army/units are you having issues with?

**Comment by rweyrauch** [comment]
I see that with newer HH2 rosters, all of the Model stats are missing.  I'll fix this.
