### ISSUE TITLE
Rosterizer support

### ISSUE THREAD

**Issue by jhargravedesign** [rweyrauch/PrettyScribe#149]
Would be great to get support for Rosterizer,

**Comment by rweyrauch** [comment]
Does rosterizer use the same XML-based format as Battlescribe?

**Comment by jhargravedesign** [comment]
It uses JSON

**Comment by mardanbeigi** [comment]
Please attach a sample JSON file, I can see if it's easy to add support. What game system are you interested in

**Comment by jhargravedesign** [comment]
[Warhammer_40k_Genestealer_Cults_Genestealer_2k.zip](https://github.com/rweyrauch/PrettyScribe/files/14361081/Warhammer_40k_Genestealer_Cults_Genestealer_2k.zip)


Thanks for looking into it. I've zipped up a json file and attached it. It'd be Warhammer 40k I'd be interested in support for :)

**Comment by mardanbeigi** [comment]
Thanks, this looks reasonable. Please also provide a corresponding battlescribe roster that exactly matches the rosterizer file -- this will help make sure the two inputs output the same thing.

**Comment by mardanbeigi** [comment]
Thanks, super helpful. It'll take me several days to commit something working, once that's in I'll let you know and we can iterate on bug fixes

**Comment by jhargravedesign** [comment]
Amazing, thanks!
