### ISSUE TITLE
No longer supporting HH 2.0

### ISSUE THREAD

**Issue by dudeisuck** [rweyrauch/PrettyScribe#152]
When trying to upload an updated list file for HH 2.0, I get an error saying: PrettyScribe does not support game type 'Horus Heresy (2022)'.

I checked with an old list file that I had used and built with the old December 1st, 2023 version and PrettyScribe still outputs with this older file and doesn't throw that error. I'm updated to the Feb 9th, 2024 update Horus Heresy v18.2.0 library in Battlescribe.

**Comment by rweyrauch** [comment]
I'll look into it.  HH2 is very much supported.
