### ISSUE TITLE
Apply page options for Kill Team squads

### ISSUE THREAD

**Issue by drwasho** [rweyrauch/PrettyScribe#158]
**Problem**
Currently the page options you see for 40k rosters doesn't appear on Kill Team rosters, which causes non-ideal formatting when trying to print:

![image](https://github.com/rweyrauch/PrettyScribe/assets/3887694/43660085-2f5a-464a-a94f-1ec4b2ee1dd2)

**Comment by mardanbeigi** [comment]
Which page options are you looking for?

@rweyrauch I can update the KT renderer to use HTML similar to the 40k render, which will allow us to add dynamic page options

**Comment by mardanbeigi** [comment]
@drwasho the print options are in, please give it a whirl. Particularly, LMK if you see any bugs in roster contents since I'm not familiar with KT
