### ISSUE TITLE
[Bug] Intercessory squad: chapter tactics not displaying 

### ISSUE THREAD

**Issue by drwasho** [rweyrauch/PrettyScribe#159]
![image](https://github.com/rweyrauch/PrettyScribe/assets/3887694/61b971e1-1431-4b3e-bed4-08bb88dfe52b)

![image](https://github.com/rweyrauch/PrettyScribe/assets/3887694/ecedc5bc-ad97-47b8-8493-9f99ac70d1a5)

**Comment by rweyrauch** [comment]
The existing Kill Team viewer does not support 'Chapter Tactics'.   These can be added.
