### ISSUE TITLE
Certain weapons are overlaying range stat

### ISSUE THREAD

**Issue by GFKennon** [rweyrauch/PrettyScribe#17]
Hey, it seems some weapons with really long names are leaking into the ranged stat slightly and overlaying over the ranged stat, I included the one I found when doing a list today.

[weapons.zip](https://github.com/rweyrauch/PrettyScribe/files/6907733/weapons.zip)
![Screenshot 2021-07-30 140920](https://user-images.githubusercontent.com/8433708/127657548-27970947-cf7d-45b5-b2bb-2e78f99bb789.png)

This is a fantastic tool btw, huge appreciation for what you have done here.

**Comment by rweyrauch** [comment]
Fixed.
