### ISSUE TITLE
Rosterizer import empty

### ISSUE THREAD

**Issue by CerealMs** [rweyrauch/PrettyScribe#177]
Hello,
When I import a .regiztry, the name is imported but other than that everything is totaly empty 

![image](https://github.com/user-attachments/assets/f079cce3-9336-45cf-9880-8e91b40a8719)

**Comment by mardanbeigi** [comment]
Please attach a copy of the .regiztry file you're importing.  You'll need to rename the file to end in .zip so that you can upload it

**Comment by CerealMs** [comment]
[Warhammer_40k_Combat_Patrol_Vardenghast.zip](https://github.com/user-attachments/files/17456443/Warhammer_40k_Combat_Patrol_Vardenghast.zip)
