### ISSUE TITLE
Hedonites and Long Datasheets

### ISSUE THREAD

**Issue by Hungry353** [rweyrauch/PrettyScribe#19]
Seems certain units are not displaying when loaded with PrettyScribe (using AOS)

the points are entered (the units in the case are The Fane Of Slaanesh and Syll'esske The Vengeful Alliance)

alongside this, when printing, datasheets for Keeper Of Secrets and Shalaxi Helbane seem to either overlap eachother when it gets to their damage charts, or they can get hidden behind the next datasheet being printed
![IT BROKEN](https://user-images.githubusercontent.com/88702647/128814515-59a19f4c-a7f1-498c-af40-51f4ecc4f659.png)
[ROSTER TEST.zip](https://github.com/rweyrauch/PrettyScribe/files/6959259/ROSTER.TEST.zip)

**Comment by rweyrauch** [comment]
Seems to be a problem when printing in landscape layouts.

**Comment by rweyrauch** [comment]
Reworked AoS display to use pure html5 (no canvas).  Canvas printing problems no longer apply.
