### ISSUE TITLE
Warcry display

### ISSUE THREAD

**Issue by Dreadaxe** [rweyrauch/PrettyScribe#21]
Possibility to make the Warcry roster display more like the actual Warcry cards?
https://waywalkerstudios.com/blank-fighter-cards/
https://stevrak.github.io/warcry-card-creator/index.html
https://stevrak.github.io/warcry-card-creator/downloads.html

**Comment by rweyrauch** [comment]
I'll look into it.  Thanks for the links.

**Comment by Dreadaxe** [comment]
Excellent!

Le mer. 1 sept. 2021 à 17:35, Rick Weyrauch ***@***.***> a
écrit :

**Comment by rweyrauch** [comment]
First (very rough) pass at a Warcry card-like layout.   Would a layout similar to this be useful?

![warcry_proto](https://user-images.githubusercontent.com/7072852/132426271-52a6dd4f-1b5a-4cc5-97bc-d12d11036194.png)

**Comment by Dreadaxe** [comment]
I like

My comments
![Comments](https://i.imgur.com/Nsp0zwR.png)

**Comment by rweyrauch** [comment]
Thanks for the input.  Here's a second pass.
![tzeentch_proto_2](https://user-images.githubusercontent.com/7072852/132544190-43b47ed1-52f4-44d5-96cb-bcffb2c1c51c.png)

**Comment by Dreadaxe** [comment]
Like more!

**Comment by rweyrauch** [comment]
I pushed an update with the new Warcry display.   There are still a few rough spots that need to fixed up.
Let me know what you think.

**Comment by Dreadaxe** [comment]
Seem great. Maybe add grey background?
