### ISSUE TITLE
Kill Team (2021)

### ISSUE THREAD

**Issue by mzsilak** [rweyrauch/PrettyScribe#22]
Create renderer and roster for KT21.
I will give it a shot this week. I am sure I will need help with graphics. In the meantime I will use placeholders from old KT.

**Comment by mzsilak** [comment]
I have a good working version. Please have a look here: https://github.com/mzsilak/PrettyScribe/tree/KT21
It seems like Roles/Specialism and Archetypes are not implemented in the source rosters, so we don't need graphs.

**Comment by rweyrauch** [comment]
Looks pretty good.  I am not familiar with the new KT rules however.

**Comment by rweyrauch** [comment]
Merged into master.
