### ISSUE TITLE
AoS - Soulblight Gravelords - Invigorating Aura missing

### ISSUE THREAD

**Issue by scottywan82** [rweyrauch/PrettyScribe#27]
The Soulblight Gravelords spell Invigorating Aura (which they all get) does not print along with the rest of the Allegiance Abilities as it does in the standard Battlescribe output, nor is it included in the separate unit entries.  I've attached an HTML file showing the output from Battlescribe if that helps.

Great job on the list output, though!

[Soulblight Army List.zip](https://github.com/rweyrauch/PrettyScribe/files/7250932/Soulblight.Army.List.zip)

**Comment by rweyrauch** [comment]
I see the error.  I'll fix the app.

Thanks.

**Comment by rweyrauch** [comment]
Fixed.
