### ISSUE TITLE
`npm start` no longer auto-reloads prettyscribe.js on localhost:8080

### ISSUE THREAD

**Issue by mardanbeigi** [rweyrauch/PrettyScribe#28]
The iterative dev loop with `npm start` is no long updating or reloading dist/prettyscribe.js. It does compile prettyscribe.js though, and webpack claims the file is emited, but I'm not sure where it's emitted too. localhost:8080 doesn't reload, and a manual reload of the page loads the old version of prettyscribe.js.

Here's some output;
`$ npm start

> prettyscribe@1.1.0 start /Users/smardan/Documents/GitHub/PrettyScribe2
> webpack-dev-server

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.86.193:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/smardan/Documents/GitHub/PrettyScribe2' directory
(node:28375) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:28375) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
asset prettyscribe.js 3.24 MiB [emitted] (name: main)
runtime modules 26.3 KiB 13 modules
modules by path ./node_modules/ 823 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 51.8 KiB 12 modules
  modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
  modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
  modules by path ./node_modules/url/ 37.4 KiB 3 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
  ./node_modules/jszip/dist/jszip.min.js 93.5 KiB [built] [code generated]
  ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
  ./node_modules/events/events.js 14.5 KiB [built] [code generated]
  ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
modules by path ./src/*.ts 274 KiB 12 modules
webpack 5.55.0 compiled successfully in 3808 ms
`
Notice `asset prettyscribe.js 3.24 MiB [emitted] (name: main)` above.  However, dist/prettyscribe.js is not updated.

I can manually update dist/prettyscribe.js by manually running `npm run build` after each edit:

`
$ npm run build

> prettyscribe@1.1.0 build /Users/smardan/Documents/GitHub/PrettyScribe2
> webpack

(node:28815) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:28815) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
asset prettyscribe.js 2.6 MiB [emitted] (name: main)
runtime modules 1.25 KiB 6 modules
modules by path ./src/*.ts 274 KiB 12 modules
modules by path ./node_modules/ 625 KiB
  ./node_modules/jszip/dist/jszip.min.js 93.5 KiB [built] [code generated]
  ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
webpack 5.55.0 compiled successfully in 3808 ms
`

`

Any idea what's up?

**Comment by rweyrauch** [comment]
No.  I've been trying to fix the reload.  It's been broken since I updated webpack.

**Comment by rweyrauch** [comment]
Rolled webpack back to v4 until I can figure out how to properly configure v5 dev-server.
