### ISSUE TITLE
Canvas vs HTML+CSS

### ISSUE THREAD

**Issue by mardanbeigi** [rweyrauch/PrettyScribe#30]
Have you considered using HTML+CSS to render data instead of canvas? Canvas has the downside that it doesn't scale well, and ends up looking a little fuzzy. I have a working demo for the renderer40k.ts, happy to clean it up and send a pull request if you'd like to take a look. LMK

**Comment by rweyrauch** [comment]
Yes. I just started to move the 40k renderer to straight html.  I have already redone the Warcry and Age of Sigmar renderers.   

For 40k my plan is mimic the look and feel of the 9th edition codex.

**Comment by rweyrauch** [comment]
Merged and pushed the changes to the main release.  Thank you for your work on this.
