### ISSUE TITLE
Wound brackets missing (ex: Redemptor Dread)

### ISSUE THREAD

**Issue by beefwellington13** [rweyrauch/PrettyScribe#42]
I'm not sure if its because I used a "Custom Name" but the wound brackets do not show for the Redemptor Dread

![image](https://user-images.githubusercontent.com/16635927/143775810-a903df6c-5774-478b-9cf2-05a2c2f2869f.png)

**Comment by mardanbeigi** [comment]
Custom Name looks to blame. Please attach a .rosz file with just the buggy unit and I can confirm

**Comment by beefwellington13** [comment]
[PrettySribe_CustomName_Test.zip](https://github.com/rweyrauch/PrettyScribe/files/7655109/PrettySribe_CustomName_Test.zip)

Attached a rosz file for you

**Comment by mardanbeigi** [comment]
Thanks, that was helpful. I submitted a fix, once that's pulled in and live the problem will be resolved
