### ISSUE TITLE
Minor changes on fork

### ISSUE THREAD

**Issue by mzsilak** [rweyrauch/PrettyScribe#5]
Hello,

As you might have noticed, I forked your work. 
It is pretty amazing, but it was chunky in some places and had issues in some other places. 

I have pretty much all changes in a single commit, so you might need to dig through if you want to merge some changes back.

My Changes:
- The models in the unit list is sometimes pretty useless. My list contains models with the same name but different loadout. The original looks like this: 
> Acolyte Leader, 5 Acolyte Hybrid, Acolyte Hybrid, Acolyte Hybrid, Acolyte Hybrid, Acolyte Hybrid 

My change is to include every model with its updates and weapons (each on a new line):
> 5x Acolyte Hybrid (Blasting Charge, Cultist Knife, Hand Flamer, Rending Claw(s))
> 3x Acolyte Hybrid (Blasting Charge, Hand Flamer, Heavy Rock Saw)
> Acolyte Hybrid (Blasting Charge, Hand Flamer, Heavy Rock Cutter)
> Acolyte Leader (Blasting Charge, Cultist Knife, Hand Flamer, Rending Claw(s))

- I repeat the force title before the unit canvas (and print the correct faction/sub-faction as well). 
> Tyranids - Genestealer Cults (The Pauper Princes)

- The general canvas is broader so it fits the width of a DIN A4 page. This works right now, but if I try to resize or change paper settings I get blurred text on canvas. No clue how to fix that.

- I adopted the table column sizes to make full use of the extra space for abilities and details. 

- I adapted the Psykers section and turned it into a single line with the same information

- I removed the Rules section. The Rules are now mentioned in "abilities" and are printed once at the end of the list. sub-faction specific rules are printed separately.

> ### Tyranids - Genestealer Cults
**Cult Ambush**
During deployment, ...
**Unquestioning Loyalty**
Each time ...

> ### The Pauper Princes
**Devoted Zealots**
You can re-roll ...

- The Models shows the same information as in the initial list, i.e. Models with gear and Weapons.

Give it a try and see if you can use some of my changes. 

kind regards, Mario

**Comment by rweyrauch** [comment]
Excellent.  I've merged your changes back into my repo.

The change look great.

**Comment by rweyrauch** [comment]
Tested.
