### ISSUE TITLE
Errors on npm start

### ISSUE THREAD

**Issue by humanaut** [rweyrauch/PrettyScribe#62]
I had this similar issue with the Start Generator, looking like it might be something with my machine. Errors attached.  Any advice? 
![image](https://user-images.githubusercontent.com/3498525/158093256-5891cd6c-68c9-491d-b166-c7f2ddacbc2e.png)
[2022-03-14T02_13_43_159Z-debug.log](https://github.com/rweyrauch/PrettyScribe/files/8241241/2022-03-14T02_13_43_159Z-debug.log)

**Comment by rweyrauch** [comment]
What version of node and npm are you using?
Currently (under Linux) I am building with Node.js v12.18.1 and npm v6.14.5.

**Comment by humanaut** [comment]
I'm pretty old (for work).

**Comment by humanaut** [comment]
I forgot I had NVM installed, so I've installed that. No errors on npm start. Thanks!
