### ISSUE TITLE
Black Coach's Damage Table doesn't display correctly

### ISSUE THREAD

**Issue by martyjhenderson** [rweyrauch/PrettyScribe#66]
Issue: When using the Black Coach from Age of Sigmar's "Death - Nighthaunt" army the Damage Table doesn't show up correctly

Example of current bug:
![BlackCoachTable](https://user-images.githubusercontent.com/6262509/163587972-49f466d4-0397-4f09-9cbc-bbc4af59be9f.png)

Expected outcome:
Have a table that shows the chart of distance and attack count by wounds taken

Example from BattleScribe:

![BlackCoachTable_bs](https://user-images.githubusercontent.com/6262509/163588200-2219e1a3-1e94-4b01-bff9-a778be7f5c12.png)

Example from AoS Mobile App:

![BlackCoachTable_App](https://user-images.githubusercontent.com/6262509/163588501-121869cb-7b82-46ce-98be-1fcc88baf953.png)

rosz file containing only Black Coach (in a zip file):

[BlackCoachOnly.zip](https://github.com/rweyrauch/PrettyScribe/files/8496687/BlackCoachOnly.zip)

Things I've tried:

- Switching optional weapon between Soulreach Grasp and Reaper Scythe
- Naming the unit
- Adding other units to the same roster

Possibly related, can open a new bug if you'd like:

The table for "Evocation of Death" doesn't appear in numerical order:

Example from PrettyScribe:

![EoD](https://user-images.githubusercontent.com/6262509/163588781-8c274cb6-a333-4025-b9c2-c061967041be.png)

As displayed in BattleScribe:

![EoD_bs](https://user-images.githubusercontent.com/6262509/163588802-0a892d75-ad9d-440d-9d73-1b329980b488.png)

**Comment by rweyrauch** [comment]
Fixed.

**Comment by martyjhenderson** [comment]
Would you like me to open a second bug report for that part with the Evocation of Death levels?

**Comment by rweyrauch** [comment]
Yes, please.  There is a general sorting problem in Prettyscribe.  Some Damage Tables are not sorted and some ability tables are not sorted.

**Comment by martyjhenderson** [comment]
Done in #67 - thanks for taking a look at all of this!
