### ISSUE TITLE
Black Coach's Evocations are not ordered

### ISSUE THREAD

**Issue by martyjhenderson** [rweyrauch/PrettyScribe#67]
A spin-off of #66 

Summary: The Black Coach (Death - Nighthaunt) has 5 Evocations of Death it gets and they are normally presented in numerical order. However, PrettyScribe doesn't place them in the same order presented

Example of bug:

![EoD](https://user-images.githubusercontent.com/6262509/163597974-dbcf2254-04eb-4eff-bff8-491d4c2b069b.png)

Example of working in BattleScribe:

![EoD_bs](https://user-images.githubusercontent.com/6262509/163598010-84cdafc5-affe-4448-9785-3ec276a1415b.png)

Example of the first two in the AoS App:

![EoD_App](https://user-images.githubusercontent.com/6262509/163598141-53ab33a4-00e2-4df9-b561-938c3bbaee71.png)

Troubleshooting tried:

- Changing weapons on Black Coach (between Reaper Scythe and Soulreach Grasp)
- Adding other models to the roster
- Naming the model in BattleScribe

Attached: 
Coach only rosz in zip file

[BlackCoachOnly.zip](https://github.com/rweyrauch/PrettyScribe/files/8497026/BlackCoachOnly.zip)

**Comment by rweyrauch** [comment]
Closing as N/A.  The Black Coach warscroll was rewritten and the bugs not longer apply.
