### ISSUE TITLE
Change font size?

### ISSUE THREAD

**Issue by dairefitz1** [rweyrauch/PrettyScribe#68]
Whenever I print out the rosters the body text is ~2mm high, which is roughly 6pt. Is there some way to increase the font size?

**Comment by rweyrauch** [comment]
Two questions.
1) What type of roster are you printing?  40k?
2) How are you printing?

**Comment by dairefitz1** [comment]
1. Yes, a 40k roster.
2. First I save to pdf. A4, default margins, fit to page width, print backgrounds. If I try and scale it up it chops off the right hand side of the boxes. Then I print the PDF. I've attached the "fit to page width" pdf and a pdf where I tried to scale it up.

[test2.pdf](https://github.com/rweyrauch/PrettyScribe/files/8512312/test2.pdf)
[test1.pdf](https://github.com/rweyrauch/PrettyScribe/files/8512313/test1.pdf)

**Comment by mardanbeigi** [comment]
Seems reasonable to have an option for how tiny text is, that way folks can choose the size they want the printout to be.

@dairefitz1 what size would you want? To test different sizes out on Chrome, once you load a roster in prettyscribe, open Chrome Dev Tools and run one of the snippets below (instructions to open @ https://developer.chrome.com/docs/devtools/open/#console and to run snippets @ https://developer.chrome.com/docs/devtools/console/#javascript).
1. `Array.from(document.styleSheets).filter(s => s.href && s.href.includes('prettyscribe.css'))[0].insertRule('.wh40k_unit_sheet { width: inherit !important;}')`
2. `Array.from(document.styleSheets).filter(s => s.href && s.href.includes('prettyscribe.css'))[0].insertRule('.wh40k_unit_sheet { width: 800px !important;}')`

LMK if you're running a different browser and I can send you instructions for that.

Right now, each datasheet has a width of 1100px, and the browser shrinks everything to make that fit. The above snippets change the width either "let the browser decide" or 800px.

**Comment by dairefitz1** [comment]
I tried out a few different widths and 800px is perfect. Font is much more readable when printed.

Thank you so much!

**Comment by mardanbeigi** [comment]
Fix is live with option "Print Larger Text", give it a spin

**Comment by dairefitz1** [comment]
Perfect!
