### ISSUE TITLE
Resonance Barb relic (Tyranids) does not show on the list

### ISSUE THREAD

**Issue by Piotr-Wachowicz** [rweyrauch/PrettyScribe#70]
Resonance Barb relic (Tyranids) does not show on the list, only the power selected from this relic shows
[resonance barb bug.zip](https://github.com/rweyrauch/PrettyScribe/files/8539730/resonance.barb.bug.zip)
.

**Comment by mardanbeigi** [comment]
Thanks Piotr, I have an idea for the fix.

Nerding out: Res barb is a selection with a sub-selection (the psychic power). The other cases I've seen like this have been weapon pairs (eg sword + board), where we flatten the sub-selections and ignore the parent selection. In this case though, we'll want to show both
