### ISSUE TITLE
40k: Adding units to a 2nd detachment causes most of the force rules and selection rules to not display

### ISSUE THREAD

**Issue by Chimpy20** [rweyrauch/PrettyScribe#80]
This relates to the 40k 9th edition data set. If a 2nd detachment is added, and a unit added to that detachment, in PrettyScribe most of the force rules and selection rules do not display. Some do, it seems a bit arbitrary. Adding a 2nd empty detachment doesn't seem to cause the problem - it seems to occur as soon as a unit is added to the 2nd detachment. The detachment type doesn't seem to effect the issue.

[DarkAngelsTest.zip](https://github.com/rweyrauch/PrettyScribe/files/9225895/DarkAngelsTest.zip)

**Comment by mardanbeigi** [comment]
Thanks for the report, pull request for fix submitted. Once that's in, you'll be good to go
