### ISSUE TITLE
Wheel too big in AoS rosters?

### ISSUE THREAD

**Issue by cahe** [rweyrauch/PrettyScribe#97]
First of all - many thanks for a great tool that I use and love :)

I'm trying to print the prettyfied roster on Google Chrome (newest stable). This is how it looks like on an A4 page:
![image](https://user-images.githubusercontent.com/3882/206488965-bf30a8a7-bfd0-472d-9d97-4345116fe7e5.png)

I feel like there's a lot of wasted space, the wheel could be smaller.

**Comment by rweyrauch** [comment]
Yes.  The wheel is too big.  I'll make some adjustments.

**Comment by rweyrauch** [comment]
What scale are you printing with?   In Chrome with the default scaling (100%) the rosters look fine.  However, when the scale is increased to 105% the roster looks like the one you posted.  See attached screen captures.

![Screenshot from 2022-12-09 20-01-29](https://user-images.githubusercontent.com/7072852/206828104-09
![Screenshot from 2022-12-09 20-02-00](https://user-images.githubusercontent.com/7072852/206828109-bdc02efb-6c2f-433b-81e9-2a0bdc28503e.png)
410820-13b9-430d-a14a-f7b576c47f60.png)

**Comment by rweyrauch** [comment]
![Screenshot from 2022-12-09 20-01-29](https://user-images.githubusercontent.com/7072852/206828195-1c07e940-804a-4204-988d-f053d5bb4d6f.png)

**Comment by cahe** [comment]
Prompted by this I tried different scales.

On default and 94-100+ the problem persists. From 93 down the wheels are smaller suddenly.
