### ISSUE TITLE
Show possible Stratagems for each unit

### ISSUE THREAD

**Issue by ScooloV** [rweyrauch/PrettyScribe#99]
There is this website https://40kroller.animetidd.is which allows to see all possible strategems for each phase for each unit. Is it possible to add such thing to PrettyScribe too? 
![Unbenannt](https://user-images.githubusercontent.com/16956415/207580807-54f314c7-e343-4d76-897a-eac2887bfa1d.PNG)

Or even have separate table where it is separated in different phases and tells e.g. MOVEMENT: Stratagem_Name1 for Unit_Name1, Unit_Name2 etc.
![Unbenannt](https://user-images.githubusercontent.com/16956415/207580984-0d411f46-840d-419c-9484-cd7d09915316.PNG)

Btw 40kroller developer wanted to cooperate with you, according to his Discord:
![Unbenannt](https://user-images.githubusercontent.com/16956415/207570220-54fb9b82-8763-4eba-864d-e5e2dbddebad.PNG)

**Comment by mardanbeigi** [comment]
Nifty idea, but that information isn't available in the roster, and I don't think PrettyScribe should make external calls to fetch it. PrettyScribe does output notes in rosters, though, so if the info was there, it would be output

**Comment by ScooloV** [comment]
But you don't need to make any external calls, just copy and download csv from Wahapedia and save it as part of PrettyScribe, as 40kroller did. 
https://wahapedia.ru/wh40k9ed/the-rules/data-export/#Data-Export

I think parsing [this small csv](https://wahapedia.ru/wh40k9ed/Stratagems.csv) and adding that info wouldn't be that hard. I would have done that, but sadly I am more C++/Python developer (and a bit JS), but not TS :(

**Comment by rweyrauch** [comment]
Prettyscribe does not contain any game data/rules.  It is simply a tool to present rosters in a readable format.  If the BSData 40k devs decide to add stratagems to the BattleScribe roster data, then Prettyscribe will be updated to display that data.
